SofCaptionThis/Models/Cat.cs
namespace SofCaptionThis.Models
{
    public class Cat
    {
        public Category[] Categories { get; set; }
        public string Id { get; set; }
        public string Url { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    }

}

SofCaptionThis/Models/Category.cs
namespace SofCaptionThis.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

}

SofCaptionThis/Models/ErrorViewModel.cs
using System;

namespace SofCaptionThis.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SofCaptionThis/Models/ViewModels/CatViewModel.cs
namespace SofCaptionThis.Models
{
    public class CatViewModel
    {
        public string Id { get; set; }
        public string Url { get; set; }
        public string Caption { get; set; }
    }
}

SofCaptionThis/Controllers/CatsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SofCaptionThis.Models;
using SofCaptionThis.Services.Implementation;
using System;
using System.Text.Json;
using System.Threading.Tasks;

namespace SofCaptionThis.Controllers
{
    public class CatsController : Controller
    {
        private readonly ICatsService _catsService;
        private readonly IMapper _mapper;
        public CatsController(ICatsService catsService, IMapper mapper)
        {
            _catsService = catsService;
            _mapper = mapper;
        }
        public async Task<ActionResult> Index()
        {
            var catData = await _catsService.GetCat();

            var cat = _mapper.Map<CatViewModel>(catData);

            return View(cat);
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Caption(string id)
        {
            var catData = await _catsService.GetCatById(id);
            var cat = _mapper.Map<CatViewModel>(catData);

            return View(cat);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Caption(CatViewModel cat)
        {
            try
            {
                var path = "D:\\json.txt";
                string json = JsonConvert.SerializeObject(cat);
                System.IO.File.WriteAllText($@"{path}", json);

                return Json(new { success = true, responseText = $"The json file has been downloaded to {path}." });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, responseText = "There has been an error." });
            }
        }
    }
}

SofCaptionThis/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SofCaptionThis.Models;
using System.Diagnostics;

namespace SofCaptionThis.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SofCaptionThis/Views/Cats/Caption.cshtml
@model SofCaptionThis.Models.CatViewModel
@{ 
    var url = Url.Action("Caption", "Cats");
}

@Html.Hidden("CaptionUrl", url)

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2>Time to caption this photo...</h2>
        <form action="@url" method="post" id="cat-form">
            <input type="hidden" name="Url" value="@Model.Url" />

            <div class="row">
                <img src="@Model.Url" alt="Some cat" class="photo" />

            </div>
            <br />
            <div class="row">
                <p>Write your caption here and save it to your computer.</p>
            </div>
            <div class="row caption">
                <input type="text" name="Caption" value="" class="float-left" />
                <button form="cat-form"
                        id="submit-cat-form"
                        type="submit"
                        class="btn btn-success float-right">
                    Create
                </button>
            </div>
        </form>
    </div>
</div>

SofCaptionThis/Views/Cats/Index.cshtml
@model SofCaptionThis.Models.CatViewModel
@{
    ViewData["Title"] = "Cats";
}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h1>Cats</h1>
        <a href="@Url.Action("Index", "Cats")" class="btn btn-success float-left">
            Show me a new cat!
        </a>
    </div>


    <div class="col-md-6 offset-md-3">
        <img src="@Model.Url" class="photo">
    </div>
</div>
<br />

<div class="row">
    <div class="col-md-6 offset-md-3">
        <p>To caption photos you need to log in.</p>
        @if (User.Identity.IsAuthenticated)
        {
            <a href="@Url.Action("Caption", "Cats", new { id = Model.Id })" class="btn btn-success float-left">
                Caption it!
            </a>
        }
    </div>
</div>

SofCaptionThis/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to SofCa(p)tionThis!</h1>
    <p>This is simple app that shows random cat photos.</p>
    <p>Registered users can add captions to photos and save those photos in json file on their computer.</p>
</div>

SofCaptionThis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SofCa(p)tionThis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SofCa(p)tionThis</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cats" asp-action="Index">Cats</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SofCaptionThis - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/cats.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>